### ISSUE TITLE
Item validation fails if unitPrice is 0

### ISSUE THREAD

**Issue by mpesari** [paytrail/paytrail-php-sdk#78]
The [OpenAPI specification](https://docs.paytrail.com/paytrail-api.yaml) states for `item.unitPrice`:

```yaml
    Item:
      type: object
      required:
        - unitPrice
        - units
        - vatPercentage
        - productCode
      properties:
        unitPrice:
          type: integer
          format: int64
          example: 1590
          minimum: 0
          maximum: 99999999
          description: Unit price of an item in currency minor unit, eg. EUR cents. VAT should be included in amount unless `usePricesWithoutVat` is set to true.
```

The API accepts items with `unitPrice` = 0, but `Paytrail\SDK\Model\Item` validation fails:

https://github.com/paytrail/paytrail-php-sdk/blob/c1df05e968abf8daae5d2159dcd9a44df7e817ba/src/Model/Item.php#L379-L381

This was changed in SDK version 2.5.1 (https://github.com/paytrail/paytrail-php-sdk/pull/74)

Which behaviour is correct, SDK or API?
